service: athena-query-executer

frameworkVersion: '3'

custom:
  config: ${file(config/${self:provider.stage}.yml)}
  accountId: ${self:custom.config.accountId}
  DATABASE: ${self:custom.config.DATABASE}
  QUERY: ${self:custom.config.QUERY}
  OUTPUT: ${self:custom.config.OUTPUT}
  OUTPUT_BUCKET: ${self:custom.config.OUTPUT_BUCKET}

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  region: ${self:custom.config.region}

functions:
  lambda:
    handler: index.athenaQueryExecuter
    role: athenaQueryExecuterRole

resources:
  Resources:
    athenaQueryExecuterRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: athenaQueryExecuterRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: athenaQueryExecuterPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
                - Effect: Allow
                  Action:
                    [
                      "s3:*",
                    ]
                  Resource: [
                    "*"
                  ]
                - Effect: Allow
                  Action: 
                    [
                      "athena:*"
                    ]
                  Resource: [
                      "*"
                    ]
                - Effect: "Allow"
                  Action: 
                    [
                      "glue:*",
                    ]
                  Resource: [
                      "*"
                    ]
