# Dev Env YAML
accountId: 000123456789
region: us-west-2
DATABASE: "contact-lens-analysis"
QUERY: 'SELECT * FROM "AwsDataCatalog"."contact-lens-analysis".contactlens JOIN "AwsDataCatalog"."ctr".flat ON "AwsDataCatalog".contact-lens-analysis".contactlens.customermetadata.ContactId = "ctr".flat.contactid'
OUTPUT: "s3://example-prod-ctr-streaming-stack-prodctrconsumerstorageda/combinedData"
OUTPUT_BUCKET: "example-prod-ctr-streaming-stack-prodctrconsumerstorageda"
