# Dev Env YAML
accountId: 060767761971
region: us-west-2
DATABASE: "contact-lens-analysis"
QUERY: 'SELECT * FROM "AwsDataCatalog"."contact-lens-analysis".contactlens JOIN "AwsDataCatalog"."ctr".flat ON "AwsDataCatalog".contact-lens-analysis".contactlens.customermetadata.ContactId = "ctr".flat.contactid'
OUTPUT: "s3://athena-contact-lens-results/combinedData"